-- Render metrics captured when a render finishes, surfaced in the Render tab.
-- duration_ms already existed (render wall-clock); these add the encode shape.
--   render_frames — total frames generated
--   fps           — frames per second of the output
--   resolution    — "WIDTHxHEIGHT" of the output frame (e.g. "1280x720")
--   aspect        — "16:9" | "9:16" | "1:1"
-- All nullable: older rows and in-flight renders simply have NULL.

ALTER TABLE renders
  ADD COLUMN IF NOT EXISTS render_frames INTEGER,
  ADD COLUMN IF NOT EXISTS fps           INTEGER,
  ADD COLUMN IF NOT EXISTS resolution    VARCHAR(20),
  ADD COLUMN IF NOT EXISTS aspect        VARCHAR(10);

COMMENT ON COLUMN renders.render_frames IS 'Total frames generated by the render job.';
COMMENT ON COLUMN renders.fps           IS 'Frames per second of the output video.';
COMMENT ON COLUMN renders.resolution    IS 'Output frame size, "WIDTHxHEIGHT".';
COMMENT ON COLUMN renders.aspect        IS 'Output aspect ratio: 16:9, 9:16, or 1:1.';
